### ISSUE TITLE
Add rate book funtion

### ISSUE THREAD

**Issue by Persian-Prince** [Persian-Prince/Innovator-s-Library#12]
Implement the rate book function according to the following conditions.
Your system should allow the user to enter any integer between 0 to 10 (both inclusive) and the final rating would be the average of all the user ratings given to the book and should be a real number.
The ratings would be given to a Book issued by a user, and not a Book Copy.
The ratings must be modifiable. Also, if a user has rated a book multiple times, then only the last rating given by the user should matter, any previous ratings should not contribute to the average rating of the book.
As an example, if there are two users U1 and U2, and they have rated a book as 8 and 10, respectively, then the average rating would be 9.0. If the user U1 later changes the rating to 9, then the average rating of the book should become 9.5.
Only a logged in user should be allowed to rate a book, but others may view the average rating of the book.

**Comment by mihir02badkur** [comment]
Please assign this to me.

**Comment by Gourav-Kr** [comment]
Sir @Persian-Prince  may I contribute to this issue?
